[workspace]
resolver = "3"
members = [ "brightness-server",
    "rust"
    # TODO:
    #  brightness server? -- just reading brightness & exposing a socket
    #  adaptive brightness server -- current thing but reading from the new socket instead
    #  separate CLI to read brightness directly

, "tsl2591"]
